config/routes.rb
Rails.application.routes.draw do

  #這些是scaffold產生的
  devise_for :accounts
  resources :posts
  resources :users
  root to:'users#index'
  #底下是手工打造的
  get '/about_us', to:"pages#about"
  get '/contact', to:"pages#contact"
  resources :acticles
  #想要/articles/2/subsribe，類似articles/2/edit
 #  resources :articles do
 #  	member do
 #  		get 'subscribe' #=>/articles/2/subsribe
 #  	end	
	
	# collection do
	# 	get 'list' #=>/articles/list
	# end	

	# resources :users do
	# 	resources :articles, shallow: true
	# end	

 #  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/account.rb
class Account < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
  #所有model共同會用到的,寫在這裡
end

app/models/article.rb
class Article < ApplicationRecord
end

app/models/post.rb
class Post < ApplicationRecord
	belongs_to :user #[kobe_notes]根據field=>user_id去與user table關聯起來
end

app/models/user.rb
class User < ApplicationRecord
	has_many :posts
end

app/controllers/acticles_controller.rb
class ActiclesController < ApplicationController
  def index
  end

  def new
  	@acticle = Article.new
  end

  def show
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about

  	#蛇都沒打,預設會到app/views/pages/about.html.erb
  	#render json:{name:"kobe",age:32}
  	@total_price = '$200/1m'
  	@kobe_age = 32
  	#render layout:false
  end	

  def contact

  end	
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :content, :user_id)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
#:authenticate_user!,
  # GET /users
  # GET /users.json
  def index
    #@users = User.all #翻譯成 select * from users;
    @users = User.page(params[:page]).per(5)#[kobe_notes] kaminari的分頁功能
    #render @users == 'render partial:'user', collection:@users, as: :user'  
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  module TestHelper
def is_adult?(age)
    if age >=18
    "<h1>成年</h1>".html_safe
    else
    "<h1>not yet 成年</h1>".html_safe
    end 
  end 
  end  

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :email)
    end
end

app/helpers/acticles_helper.rb
module ActiclesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
	#全站在用寫在這邊
	# def is_adult?(age)
	#   if age >=18
	# 	"<h1>成年</h1>".html_safe
	#   else
	# 	"<h1>not yet 成年</h1>".html_safe
	#   end	
	# end	

	def is_adult?(age)
	  if age >=18
		content_tag :div, content_tag(:p,"888成年"),class:["strong","highlight"] 
				
		
	  else
		content_tag :h1 do
		  "not yet 成年"		
		end
		
	  end	
	end	
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/acticles/index.html.erb
<h1>Acticles#index</h1>
<%= link_to '新增文章', new_acticle_path%>

app/views/acticles/new.html.erb
<h1>Acticles#new</h1>
<%= form_for(@acticle) do |f|%>
	<%= f.label :title%>
	<%= f.text_field :title%>
	<%= f.submit %>
<%end%>

app/views/acticles/show.html.erb
<h1>Acticles#show</h1>
<p>Find me in app/views/acticles/show.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsBlog</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  	<!--[kobe_notes] 選單放這,所有的頁面就可以一次全改 -->
  	<div class="container">
    	<%= yield %>
      <%= yield :hole_from_about%>
      <!--只有在提供:hole_from_about這個symble才會在此處輸出-->
	</div>
  </body>
</html>

app/views/pages/about.html.erb
<h1>About</h1>

<%= link_to 'Contact', contact_path%>

<%content_for :hole_from_about do%>
<h2> HI, hole here, i am kobe, age=<%="#{@kobe_age}"%></h2>
<% end %>

<%= render partial:'components/ad', locals:{price:@total_price,tel:"0926978178"}%>

<%= is_adult?(20)%>

app/views/pages/contact.html.slim
h1 10點以後不要打給我~因為~我睡啦~~~~

= link_to 'About', about_us_path
table
   thead
     tr
       th 123
       th 456

   tbody
     tr
       td xxx
       td yyy   

app/views/posts/_form.html.erb
<%= form_for(post) do |f| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :content %>
    <%= f.text_area :content %>
  </div>

  <div class="field">
    <%= f.label :user_id %>
    <%= f.number_field :user_id %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Posts</h1>

<table class="table">
  <thead>
    <tr>
      <th>Title</th>
      <th>Content</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.title %></td>
        <td><%= post.content %></td>
        <td><%= post.user.name %></td>
        <td><%= link_to 'Show', post %></td>
        <td><%= link_to 'Edit', edit_post_path(post) %></td>
        <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Post', new_post_path %>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @post.title %>
</p>

<p>
  <strong>Content:</strong>
  <%= @post.content %>
</p>

<p>
  <strong>User:</strong>
  <%= @post.user_id %>
</p>

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>

app/views/users/_form.html.erb
<%= simple_form_for(user) do |f| %>
<!--  
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
-->
  <%= f.input :name%>
  <%= f.input :email%>
  <%= f.submit%>
<% end %>

app/views/users/_user.html.erb
<tr>
  <td><%= user.name %></td>
    <td><%= user.email %></td>
      <td><%= link_to 'SHOW', user, class:"btn btn-success" %></td>
        <td><%= link_to 'Edit', edit_user_path(user),class:"btn btn-warning"%></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' }, class:"btn btn-danger"%></td>
</tr>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<%= paginate @users, theme:'twitter-bootstrap-3', :pagination_class => "pagination-small pagination-centered"%>
<table class="table table-hover table-condensed table-bordered">
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <!-- 我要render一部份(partial)的頁面
    這個頁面的實際檔名叫'_user.html.erb'
    但我要一直重複用這個頁面, 因為我的資料很多筆
    所以我給一個參數collection:值是@users(複數)
    這個users可以取出很多個user的變數給partial頁面使用
    -->
    <%= render partial:'user', collection:@users, as: :user%>
    <!--有了上面這一行就可以在抽出部分頁面邏輯
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= link_to 'Show', user, class:"btn btn-success" %></td>
        <td><%= link_to 'Edit', edit_user_path(user),class:"btn btn-warning"%></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' }, class:"btn btn-danger"%></td>
      </tr>
    <% end %>
  -->
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path, class:"btn btn-primary" %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>